services:
  nginx:
    image: nginx:latest
    container_name: autumn-ui-nginx
    restart: always
    ports:
      - "80:80"  # Map HTTP traffic to NGINX
      - "443:443"  # Optional: Map HTTPS traffic if using SSL
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Mount custom NGINX config
      - /etc/ssl/hs.codes:/etc/ssl/hs.codes:ro  # Mount SSL files from VPS
    #  - /etc/letsencrypt:/etc/letsencrypt:ro  # Optional: Mount Let's Encrypt certificates
    depends_on:
      - web
    networks:
      - autumn-ui-network

  web:
    image: "sageprojects/hscodes:${GITHUB_RUN_NUMBER}"
    container_name: autumn-ui-web
    restart: always
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - StoreDatabaseSettings__ConnectionString=${CONNECTION_STRING}
      - Auth0__Domain=${AUTH0_DOMAIN}
      - Auth0__Audience=${AUTH0_AUDIENCE}
      - SiteSettings__GroqApiKey=${GROQAPIKEY}
      - SiteSettings__GroqModel=llama-3.1-8b-instant
      - SiteSettings__Threshold=0.1
    networks:
      - autumn-ui-network

networks:
  autumn-ui-network:
    driver: bridge
